### PR TITLE
Add info about Stargate to README.md

### LINKED ISSUE #5: Info about Stargate
We can add more information about Stargate for other people to understand better!

### PR DESCRIPTION
**Pull request by SashoStoichkov**
More information about Stargate 👇🏻 

Docs: https://stargate.io/docs/stargate/1.0/quickstart/quickstart.html

Created on this Live Stream: https://www.youtube.com/watch?v=pekHBfYd1-Q

closes #5

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
closes #9 also

**Comment by srinath1412001** [comment]
Pull Request #15  covers it.

**Review by Vyvy-vi — COMMENTED** [review]
LGTM-! but #15 resolves this

**Comment by SashoStoichkov** [comment]
Thank you 👍🏻

**Comment by eddiejaoude** [comment]
Great team work 💪  thank you 🤓

**Pull request closed without merging**
