### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by moeinio**
add stargate video to readme

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Review by srinath1412001 — COMMENTED** [review]
LGTM (But can be improved in future)

**Comment by Vyvy-vi** [comment]
Maybe the title can be more descriptive?

**Comment by moeinio** [comment]
apparently github removes some metadata, therefore it looks a bit different than expected in MD, i will have a look at it later.

**Pull request merged**
