### PR TITLE
docs: PR Template

### PR DESCRIPTION
**Pull request by AllanRegush**
partially completes #8 

Initial PR Template

### CODE REVIEW

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
This file should be in the root `.github` directory, I believe - not nested in the `.github/workflows` directory.

**Comment by eddiejaoude** [comment]
Thanks @AllanRegush 👍 

I think @nhcarrigan is correct, it needs to be moved up a directory https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by AllanRegush** [comment]
Ah, yeah I think that was by mistake

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by eddiejaoude** [comment]
Thanks all 👍

**Pull request merged**
