### PR TITLE
Added features.md file for suggesting features

### PR DESCRIPTION
**Pull request by reapedjuggler**
We can list all our features in this file

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
I think this can be added in the README.md file

**Review by Vyvy-vi — COMMENTED** [review]
This looks nice-!
I think this can be rather added in the `README.md` file

**Comment by reapedjuggler** [comment]
I think we can have a different file for features so that there's a flow maintained :D

**Comment by Vyvy-vi** [comment]
Not sure.
Thoughts @eddiejaoude ?

**Comment by nhcarrigan** [comment]
I would worry that tracking features within the file while also tracking them via issues will lead to discrepancies. IMHO, it's better to keep features as GitHub issues.

**Comment by AllanRegush** [comment]
I agree with @nhcarrigan.

**Comment by Vyvy-vi** [comment]
Moreover, I think _eventually_ the bot's `help` command would be self-documenting with respect to the features of the bot.

**Comment by eddiejaoude** [comment]
Thank you for the PR @reapedjuggler and everyones suggestions 👍 

I think this would get out of date very quickly. It would be best to track new features with issues, and if we use http://conventionalcommits.org we can track current features available.

Lets get started and we can always revisit this later on, maybe with high level features available or similar.

**Pull request closed without merging**
