### PR TITLE
fix: channel id outputs coming due to discord.js v updates

### PR DESCRIPTION
**Pull request by ghost**
Fixes #

#### Proposed Changes

- Fixes the problem of id mentions added in the new discord.js version

### CODE REVIEW

**Comment by eddiejaoude** [comment]
This will now break for the other version. We should lock down the version to be consistent and make sure we lock it down to the latest version

**Comment by ghost** [comment]
> This will now break for the other version. We should lock down the version to be consistent and make sure we lock it down to the latest version

I mean we can upgrade to latest on both platforms

**Comment by eddiejaoude** [comment]
We should not need to upgrade on both not even sure how we could do that, we should upgrade in the repo and make sure that everywhere is using the `package.lock` to be consistent

**Comment by Vyvy-vi** [comment]
Do we really need to mention them again?
I think 2 mentions for a simple test command, is a bit too much

**Comment by ghost** [comment]
> Do we really need to mention them again?
> I think 2 mentions for a simple test command, is a bit too much

We don't exactly use the mention again, we keep the mention. If we don't want to keep the mention I can introduce changes?

**Comment by adityaraute** [comment]
What is the update on this? What are the requirements exactly?

**Comment by eddiejaoude** [comment]
I can't remember the original discussion. I might mark this repo as archive for the moment

**Pull request closed without merging**
